### ISSUE TITLE
아주 간단하게 내용만 입력했는데, 등록이 안돼요

### ISSUE THREAD

**Issue by dain7672** [wwh-techcamp-2018/team4-unnies#123]
이미지 없구
카테고리 국찌개
음식명 :qnam:
제목 4
무료
내용은 없구
나눔장소  r r
확인 눌렀는데 별다른 알림은 안주고 등록은 안되네요

![image](https://user-images.githubusercontent.com/29906076/44573617-1275bc80-a7c2-11e8-9eff-758ac1a9381a.png)
이렇게 떴ㅇ어요!

**Comment by minsungryu** [comment]
로그인하지 않아서 발생한 이슈입니다. 얼른 연동해놓을게요!
